# Generated by Django 4.2.7 on 2023-11-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phoneno', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=700)),
            ],
        ),
    ]
