# Generated by Django 4.2.7 on 2023-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookstore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=500)),
                ('auther', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=200)),
                ('coverpic', models.ImageField(upload_to='images/images')),
            ],
        ),
    ]
