# Generated by Django 4.2.7 on 2023-12-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktwo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=500)),
                ('book_auther', models.CharField(max_length=500)),
                ('book_genre', models.CharField(max_length=100)),
                ('book_nationality', models.CharField(max_length=200)),
                ('book_link', models.CharField(max_length=500)),
                ('book_coverpic', models.ImageField(upload_to='images/images')),
            ],
        ),
    ]
